### ISSUE TITLE
How to import MessagesService from redis-smq-monitor 

### ISSUE THREAD

**Issue by kaliprasadkandula** [weyoss/redis-smq-monitor#3]
hello everyone ,I am using {"name": "redis-smq-monitor",
  "version": "7.2.1"} redis smq monitor ,while using we have a consumer issue so i thought of to check the messages in the queue using getScheduledMessages of MessageService class of redis-smq-monitor but I was not able to import MessageService into my typescriptcode 
  `import  MessagesService from 'redis-smq-monitor'`

can anyone help me with this issue

**Comment by weyoss** [comment]
> import  MessagesService from 'redis-smq-monitor'

`redis-smq-monitor` does not provide such service.  Use `MessageManager` from `redis-smq`.

See https://github.com/weyoss/redis-smq/blob/master/docs/api/message-manager.md
